### PR TITLE
feat: pin dependencies (good security best practice)

### PR DESCRIPTION
**Pull request by theexiile1305**
Pinning dependencies is a very good security best practice because it specifies where images will be downloaded and checks the integrity of the base image.

### CODE REVIEW

**Comment by theexiile1305** [comment]
@renezoller What do you think about this approach?

**Comment by renezoller** [comment]
Thank you for suggestion. Could you pleased update the version numbers to the latest versions?

**Comment by theexiile1305** [comment]
@renezoller Done. I've just updated the hashes to the actual version.

**Review by renezoller — APPROVED** [review]
We have to change the sha fingerprints to the multi-arch manifest, to support multi-arch builds

**Comment by renezoller** [comment]
Thank you for your contribution!

**Pull request merged**
